apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    name: openebs
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: openebs
  namespace: kube-system
  # https://github.com/openebs/openebs
spec:
  chart: stable/openebs
  helmVersion: v3.0+unreleased
  set:
    rbac.enabled: "true"
    ssl.enabled: "true"
    metrics.prometheus.enabled: "true"
    kubernetes.ingressEndpoint.useDefaultPublishedService: "true"
    targetNamespace: openebs