name: k3OS build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the k3OS
      run: make
    - uses: actions/upload-artifact@v1.0.0
    - name: Upload iso
      with:
        name: k30siso
        path: ./output/
      id: publish-iso
